@Library('shared-library@main') _
pipeline {
    agent any

    stages {
        
        stage("deploy") {
            steps {
                script{
                    def config=[namespace:"app1",yaml:"k8s/app1.yaml"]
                    deployApp(config)
                }
            }
        }
    }

    post {
        success {
            echo 'app1 deploy completato con successo'
        }
        failure {
            echo 'Errore nel deploy App1'
        }
    }
}
